//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnchantsOrder.Demo.Properties.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnchantsOrder.Demo.Properties.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Added 的本地化字符串。
        /// </summary>
        internal static string AddedFormat {
            get {
                return ResourceManager.GetString("AddedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current language is changed to {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguageChangedFormat {
            get {
                return ResourceManager.GetString("CurrentLanguageChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current language is {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguageFormat {
            get {
                return ResourceManager.GetString("CurrentLanguageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the enchantments which you want to enchant 的本地化字符串。
        /// </summary>
        internal static string EnchantmentArgument {
            get {
                return ResourceManager.GetString("EnchantmentArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enchants.en-US.json 的本地化字符串。
        /// </summary>
        internal static string EnchantsFileName {
            get {
                return ResourceManager.GetString("EnchantsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function cancelled 的本地化字符串。
        /// </summary>
        internal static string FunctionCancelled {
            get {
                return ResourceManager.GetString("FunctionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the command (type exit to quit): 的本地化字符串。
        /// </summary>
        internal static string InputCommand {
            get {
                return ResourceManager.GetString("InputCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the name of enchantment (type q to order): 的本地化字符串。
        /// </summary>
        internal static string InputEnchantment {
            get {
                return ResourceManager.GetString("InputEnchantment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the name of item (type exit to quit): 的本地化字符串。
        /// </summary>
        internal static string InputItem {
            get {
                return ResourceManager.GetString("InputItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the language code to change language (type exit to quit): 的本地化字符串。
        /// </summary>
        internal static string InputLanguageCode {
            get {
                return ResourceManager.GetString("InputLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the item which you want to list enchantments 的本地化字符串。
        /// </summary>
        internal static string ItemArgument {
            get {
                return ResourceManager.GetString("ItemArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the language code you want to change 的本地化字符串。
        /// </summary>
        internal static string LangArgument {
            get {
                return ResourceManager.GetString("LangArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the language of this program 的本地化字符串。
        /// </summary>
        internal static string LangCommand {
            get {
                return ResourceManager.GetString("LangCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List ordered enchantments of item 的本地化字符串。
        /// </summary>
        internal static string ListCommand {
            get {
                return ResourceManager.GetString("ListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found enchantment named {0} 的本地化字符串。
        /// </summary>
        internal static string NotFoundEnchantmentFormat {
            get {
                return ResourceManager.GetString("NotFoundEnchantmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found item named {0} 的本地化字符串。
        /// </summary>
        internal static string NotFoundItemFormat {
            get {
                return ResourceManager.GetString("NotFoundItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordering the enchantments 的本地化字符串。
        /// </summary>
        internal static string OrderCommand {
            get {
                return ResourceManager.GetString("OrderCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the penalty of your item which you want to enchant 的本地化字符串。
        /// </summary>
        internal static string PenaltyOption {
            get {
                return ResourceManager.GetString("PenaltyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A demo of EnchantsOrder which can order enchantments 的本地化字符串。
        /// </summary>
        internal static string RootCommand {
            get {
                return ResourceManager.GetString("RootCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start ordering... 的本地化字符串。
        /// </summary>
        internal static string StartOrdering {
            get {
                return ResourceManager.GetString("StartOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown command 的本地化字符串。
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
